
import '../globals.css'
import '../../public/asset/css/feather.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClientCookiesProvider } from '@/context/CookieProvider'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className="light"> 
      <ClientCookiesProvider value={cookies().getAll()}>
      {children}
      </ClientCookiesProvider>
      </body>
      
     
    </html>
  )
}
